version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: capsul-postgres
    environment:
      POSTGRES_DB: capsul_db
      POSTGRES_USER: capsul_user
      POSTGRES_PASSWORD: capsul_pass
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U capsul_user -d capsul_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: capsul-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:latest
    container_name: capsul-mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    restart: unless-stopped

  metabase:
    image: metabase/metabase:latest
    container_name: capsul-metabase
    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: /metabase-data/metabase.db
      MB_EMBEDDING_SECRET_KEY: capsul-metabase-secret-key-2024
    ports:
      - "3001:3000"
    volumes:
      - metabase_data:/metabase-data
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  metabase_data:
    driver: local

networks:
  default:
    name: capsul-network